In [1]:
import os, sys, math
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:

# Read Data File

data = pd.read_csv("/Users/sidhandoo/Documents/USF/Annual Project Work/ran_peps_netMHCpan40_predicted_A0201_reduced_cleaned_balanced.csv", sep='\t')
data.head() # Shows the data structure for first few rows. Peptide Column is categorical value. Target column Label_char also is a catgeorical value.

data.describe() # Shows summary of the numerical attributes
data.info() # There are 23760 instances in the data set.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23760 entries, 0 to 23759
Data columns (total 4 columns):
peptide      23760 non-null object
label_chr    23760 non-null object
label_num    23760 non-null int64
data_type    23760 non-null object
dtypes: int64(1), object(3)
memory usage: 742.6+ KB


In [39]:
# Prepare the Data for Machine Learning Algorithm

x = data.drop(columns=["label_num", "data_type", "label_chr"])

y = data.drop(columns=["peptide", "label_chr", "data_type"])


In [40]:
print(x)

         peptide
0      LLTDAQRIV
1      LMAFYLYEV
2      VMSPITLPT
3      SLHLTNCFV
4      RQFTCMIAV
5      HQRLAPTMP
6      FMNGHTHIA
7      KINPYFSGA
8      WLLIFHHCP
9      NIWLAIIEL
10     KIMPYVAQF
11     AIWERACTI
12     MRYRVSVHP
13     VLNGYSWFA
14     WIWGIQYLL
15     VILSFCQNK
16     SNKGTYMMR
17     DRNSMMHYG
18     SLTHVPCYV
19     LMWDMRTRM
20     NLWDATMKT
21     SMNNSHYMV
22     CDPHGYQIY
23     IIADHDYYM
24     PLNPSYIKV
25     MLPPWGACV
26     MPMMRAHGR
27     YIEEVTMEF
28     QLVAENEEV
29     LVMTEDMAI
...          ...
23730  ILKDDVMAC
23731  QMLITMFQV
23732  QWGDTQGRM
23733  KKNMVAYMD
23734  SMIYDARAL
23735  YIGVWKWMV
23736  SLFGGQMKM
23737  FIWRKNMVA
23738  PCMKAIMPK
23739  TLATVRNNV
23740  LSDYKCYEP
23741  IHSYRPITM
23742  YLVQPAHNA
23743  ALDCFFWFI
23744  KLSSWGCEL
23745  FEVVSIGFI
23746  EMQCMRKTA
23747  SMNWDQETI
23748  SQANGHIWQ
23749  TWCGGKQFI
23750  TINEHINTL
23751  LMWGSHVQL
23752  VLEWVNAMI
23753  FQDDQTMSM
23754  ITYWWSFYA
23755  ILRAFLSSL
23756  QTYDEIH

In [4]:
print(y)

       label_num
0              1
1              2
2              1
3              1
4              1
5              0
6              2
7              1
8              0
9              1
10             1
11             1
12             0
13             2
14             2
15             0
16             0
17             0
18             2
19             1
20             2
21             2
22             0
23             2
24             1
25             2
26             0
27             1
28             2
29             1
...          ...
23730          1
23731          1
23732          0
23733          0
23734          1
23735          1
23736          2
23737          1
23738          0
23739          1
23740          0
23741          0
23742          2
23743          1
23744          1
23745          0
23746          0
23747          1
23748          0
23749          0
23750          2
23751          2
23752          1
23753          2
23754          1
23755          1
23756         

In [5]:
#Peptide encoding equence using the 20 Amino acids labels tha t form a peptide bond 

codes = ['A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L',
         'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y']

In [6]:
def one_hot_encode(seq):
    o = list(set(codes) - set(seq))
    s = pd.DataFrame(list(seq))
    x = pd.DataFrame(np.zeros((len(seq),len(o)),dtype=int),columns=o)
    a = s[0].str.get_dummies(sep=',')
    a = a.join(x)
    a = a.sort_index(axis=1)
    #show_matrix(a)
    e = a.values.flatten()
    return e

In [7]:
pep = 'ALDFEQEMT'

In [8]:
# Perform One Hot Encoding pm pep
e = one_hot_encode(pep)
print(e)

[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]


In [9]:
# create an object to hold loop results
print("length of x:" + str(len(x)))

length of x:23760


In [10]:
x = x.values
print("x length after removing header: " + str(len(x)))
x_loop = []
for i in x:
    x_loop.append(one_hot_encode(i))
    #print(x_loop)

print("x_loop length: " + str(len(x_loop)))


x length after removing header: 23760
x_loop length: 23760


In [11]:
x = np.asmatrix(x_loop)
y = y.as_matrix()

print(len(x))
print(len(y))



23760
23760


/Users/sidhandoo/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


In [13]:
print(x)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]


# Data Partition for Test and Train

In [14]:
# Perform Data Partition Split to creat Test and Train

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=64)



In [15]:
print(y_test)

[[1]
 [2]
 [2]
 ...
 [0]
 [0]
 [2]]


In [16]:
print(y_train)

[[2]
 [2]
 [2]
 ...
 [2]
 [1]
 [0]]


# Random Forest Classifier

In [31]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

rnd_clf = RandomForestClassifier(n_estimators=500, n_jobs=-1) 

rnd_clf.fit(x_train, y_train)

test_y_pred_rf = rnd_clf.predict(x_test)

print(accuracy_score(y_test, test_y_pred_rf))

/Users/sidhandoo/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


0.4346240179573513


In [22]:
from sklearn.tree import DecisionTreeClassifier 
from sklearn.linear_model import SGDClassifier 
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import VotingClassifier


dtree_clf = DecisionTreeClassifier(max_depth=6)
log_clf = LogisticRegression(multi_class='multinomial', solver = 'lbfgs', C=10, max_iter=1000)
sgd_clf = SGDClassifier(max_iter=10000, tol=1e-3)

voting_clf = VotingClassifier(
            estimators=[('dt', dtree_clf), ('lr', log_clf), ('sgd', sgd_clf)],
            voting='hard')

voting_clf.fit(x_train, y_train)

test_y_pred = voting_clf.predict(x_test)

/Users/sidhandoo/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/sidhandoo/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [26]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_test, test_y_pred))

0.4107744107744108


# Inspect each Classifier's Accuracy¶

In [29]:
for clf in (dtree_clf, log_clf, sgd_clf, voting_clf):
    clf.fit(x_train, y_train)
    test_y_pred = clf.predict(x_test)
    print(clf.__class__.__name__, accuracy_score(y_test, test_y_pred))

DecisionTreeClassifier 0.4068462401795735
LogisticRegression 0.4346240179573513


/Users/sidhandoo/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/sidhandoo/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SGDClassifier 0.42326038159371493


/Users/sidhandoo/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:219: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/sidhandoo/anaconda3/lib/python3.6/site-packages/sklearn/preprocessing/label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


VotingClassifier 0.4131593714927048


# Bagging classifier

In [24]:
# Out of Bag Evaluation

from sklearn.ensemble import BaggingClassifier 

bag_clf = BaggingClassifier( 
            SGDClassifier(), n_estimators= 70, 
            max_samples= 100, bootstrap=True, n_jobs=-1, oob_score=True) 

bag_clf.fit(x_train, y_train)
bag_clf.oob_score_

/Users/sidhandoo/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/bagging.py:621: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.4216570466570467

# Stochastic Gradient Boosting Classifier¶

In [38]:
# Use GradientBoosting

from sklearn.ensemble import GradientBoostingClassifier

gbclf = GradientBoostingClassifier(max_depth= 5, n_estimators= 500, learning_rate=0.1, subsample=0.75) 

gbclf.fit(x_train, y_train)

/Users/sidhandoo/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=5,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=500,
              n_iter_no_change=None, presort='auto', random_state=None,
              subsample=0.75, tol=0.0001, validation_fraction=0.1,
              verbose=0, warm_start=False)

In [37]:
test_y_pred = gbclf.predict(x_test)

print(accuracy_score(y_test, test_y_pred))

0.4346240179573513
